//
// Created by mq on 16-4-12.
//

#ifndef MALLOC_3_CPP_CLINITALLOCATEDMOMORY_H
#define MALLOC_3_CPP_CLINITALLOCATEDMOMORY_H


class CLInitAllocatedMomory {

};


#endif //MALLOC_3_CPP_CLINITALLOCATEDMOMORY_H
