//
// Created by mq on 16-4-12.
//

#ifndef MALLOC_3_CPP_CLPERTHEADHEAPCONTROLER_H
#define MALLOC_3_CPP_CLPERTHEADHEAPCONTROLER_H


class CLPerTheadHeapControler {

};


#endif //MALLOC_3_CPP_CLPERTHEADHEAPCONTROLER_H
